### ISSUE TITLE
Server Crash - Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by rckymtnrfc** [Dplayend/OdysseyHUD#10]
Forge 40.1.0
Odyssey HUD 1.18.2-3.1
Cloth Config 6.2.57

Full server log - https://pastebin.com/1dDGanBS

Mod still works if client side only but then unfortunately, the Curios slots are not available.

**Comment by Dplayend** [comment]
fixed, thanks for you report

**Comment by rckymtnrfc** [comment]
Sorry, I'm still seeing a crash on the server with odysseyhud-forge-1.18.2-3.2.

Server log - https://pastebin.com/6kqzfMav  (at line 464)

**Comment by Khaeops** [comment]
I second this, experiencing the issue with 1.18.2-3.2 on Forge 40.1.0.

**Comment by Dplayend** [comment]
now is fixed in the 3.4 forge, sorry for the issues

[https://i.imgur.com/SyNNMcU.png](url)

**Comment by Dplayend** [comment]
now its really fixed, sorry for the trouble
[https://imgur.com/XglaTy6.png](url)

**Comment by rckymtnrfc** [comment]
Thanks!
